# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [18]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [19]:
import pandas as pd
import datetime

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [20]:
data_url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data'
data = pd.read_table(data_url, sep = "\s+", parse_dates = [[0,1,2]]) 
data.head()

/var/folders/6x/wgh739ls5z333f70z53v36600000gn/T/ipykernel_19801/900062794.py:2: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_table is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  data = pd.read_table(data_url, sep = "\s+", parse_dates = [[0,1,2]])
/var/folders/6x/wgh739ls5z333f70z53v36600000gn/T/ipykernel_19801/900062794.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data = pd.read_table(data_url, sep = "\s+", parse_dates = [[0,1,2]])

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [21]:
# The problem is that the dates are 2061 and so on...

# function that uses datetime
def fix_century(x):
  year = x.year - 100 if x.year > 1989 else x.year
  return datetime.date(year, x.month, x.day)

# apply the function fix_century on the column and replace the values to the right ones
data['Yr_Mo_Dy'] = data['Yr_Mo_Dy'].apply(fix_century)

# data.info()
data.head()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [22]:
# transform Yr_Mo_Dy it to date type datetime64
data["Yr_Mo_Dy"] = pd.to_datetime(data["Yr_Mo_Dy"])

# set 'Yr_Mo_Dy' as the index
data = data.set_index('Yr_Mo_Dy')

data.head()
# data.info()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [23]:
data.isnull().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [24]:
data.notnull().sum()

RPT    6568
VAL    6571
ROS    6572
KIL    6569
SHA    6572
BIR    6574
DUB    6571
CLA    6572
MUL    6571
CLO    6573
BEL    6574
MAL    6570
dtype: int64

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [25]:
data.fillna(data.mean()).values.flatten().mean()

np.float64(10.227982360836936)

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [26]:
data.agg(['mean','std'])

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [27]:
data.T.agg(['min','max','mean','std']).T

             min    max       mean       std
Yr_Mo_Dy
1961-01-01  9.29  18.50  13.018182  2.808875
1961-01-02  6.50  17.54  11.336364  3.188994
1961-01-03  6.17  18.50  11.641818  3.681912
1961-01-04  1.79  11.75   6.619167  3.198126
1961-01-05  6.17  13.33  10.630000  2.445356
...          ...    ...        ...       ...
1978-12-27  8.08  40.08  16.708333  7.868076
1978-12-28  5.00  41.46  15.150000  9.687857
1978-12-29  8.71  29.58  14.890000  5.756836
1978-12-30  9.13  28.79  15.367500  5.540437
1978-12-31  9.59  27.29  15.402500  5.702483

[6574 rows x 4 columns]

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [32]:
data[data.index.month == 1].mean()

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [34]:
data.groupby(data.index.year).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

### Step 13. Downsample the record to a monthly frequency for each location.

In [37]:
data.groupby(data.index.to_period('M')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226
1961-02,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
1961-03,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
1961-04,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
1961-05,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
1978-09,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
1978-10,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
1978-11,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
1978-12,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

### Step 14. Downsample the record to a weekly frequency for each location.

In [38]:
data.groupby(by = data.index.to_period("W")).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1960-12-26/1961-01-01,15.040000,14.960000,13.170000,9.290000,NaN,9.870000,13.670000,10.250000,10.830000,12.580000,18.500000,15.040000
1961-01-02/1961-01-08,13.541429,11.486667,10.487143,6.417143,9.474286,6.435714,11.061429,6.616667,8.434286,8.497143,12.481429,13.238571
1961-01-09/1961-01-15,12.468571,8.967143,11.958571,4.630000,7.351429,5.072857,7.535714,6.820000,5.712857,7.571429,11.125714,11.024286
1961-01-16/1961-01-22,13.204286,9.862857,12.982857,6.328571,8.966667,7.417143,9.257143,7.875714,7.145714,8.124286,9.821429,11.434286
1961-01-23/1961-01-29,19.880000,16.141429,18.225714,12.720000,17.432857,14.828571,15.528571,15.160000,14.480000,15.640000,20.930000,22.530000
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-11-27/1978-12-03,14.934286,11.232857,13.941429,5.565714,10.215714,8.618571,9.642857,7.685714,9.011429,9.547143,11.835714,18.728571
1978-12-04/1978-12-10,20.740000,19.190000,17.034286,9.777143,15.287143,12.774286,14.437143,12.488571,13.870000,14.082857,18.517143,23.061429
1978-12-11/1978-12-17,16.758571,14.692857,14.987143,6.917143,11.397143,7.272857,10.208571,7.967143,9.168571,8.565714,11.102857,15.562857
1978-12-18/1978-12-24,11.155714,8.008571,13.172857,4.004286,7.825714,6.290000,7.798571,8.667143,7.151429,8.072857,11.845714,18.977143
1978-12-25/1978-12-31,14.951429,11.801429,16.035714,6.507143,9.660000,8.620000,13.708571,10.477143,10.868571,11.471429,12.947143,26.844286

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [39]:
data.groupby(data.index.to_period('M')).agg(['min','max','mean','std']).head(52)

           RPT                               VAL                              \
           min    max       mean       std   min    max       mean       std
Yr_Mo_Dy
1961-01   4.92  25.04  14.841333  4.955164  3.42  23.91  11.988333  4.807840
1961-02   6.04  25.80  16.269286  5.278793  7.08  24.21  14.975357  4.208606
1961-03   4.88  18.25  10.890000  3.799952  2.58  17.00  11.296452  3.789808
1961-04   4.00  21.09  10.722667  4.557746  3.71  15.41   9.427667  3.407936
1961-05   3.54  23.00   9.860968  4.613944  3.58  19.79   8.850000  4.364497
1961-06   4.00  15.92   9.904138  2.877174  3.25  14.54   8.520333  2.816621
1961-07   3.04  22.50  10.614194  5.559626  2.92  19.29   8.221613  4.181677
1961-08   2.88  18.91  12.035000  4.088799  4.42  22.00  10.133871  4.008152
1961-09   5.00  28.75  12.531000  6.166650  1.13  22.08   9.656897  5.038685
1961-10   3.13  28.62  14.289667  6.971204  2.75  21.25  10.915806  5.154063
1961-11   5.46  23.75  10.896333  4.097744  3.29  18.71   8.592667  3.883569
1961-12   5.04  24.41  14.973548  4.898988  3.08  21.37  11.903871  4.038147
1962-01   0.67  31.13  14.783871  7.767935  3.13  26.54  13.160323  6.611289
1962-02   5.66  30.13  15.844643  6.572137  4.75  25.17  12.041429  5.541822
1962-03   4.33  35.80  11.634333  6.108636  2.25  31.63   8.602258  5.722100
1962-04   3.58  32.58  12.160667  7.931489  1.42  23.75   9.676667  5.726741
1962-05   5.54  21.04  12.745806  4.162250  7.62  16.42  10.865484  2.477664
1962-06   1.00  22.13  10.305667  5.019292  4.29  21.04   9.677000  4.438830
1962-07   3.08  18.88   9.981935  4.121338  2.67  16.62   8.370645  3.540430
1962-08   0.96  24.67  10.964194  5.035314  2.33  20.12   9.694194  3.908694
1962-09   3.83  26.83  11.176333  4.856198  3.08  16.75   9.507000  3.240812
1962-10   1.50  21.50   9.699355  5.382874  0.87  22.79   8.063548  5.456014
1962-11   2.96  24.96  11.071333  5.672076  1.50  21.59   7.984000  4.898325
1962-12   5.75  30.91  16.785484  5.771698  2.58  24.79  13.753548  4.774371
1963-01   5.41  28.21  14.868387  6.391997  1.54  21.84  11.112903  5.593110
1963-02   4.08  22.83  14.418929  4.838272  1.92  22.21  11.876429  5.929131
1963-03   4.38  27.46  14.853871  6.293998  2.62  22.67  12.271290  5.554471
1963-04   3.88  27.08  11.616000  5.787109  3.13  20.67  10.138000  4.292342
1963-05   2.04  30.91  12.879677  6.288383  2.21  22.17  11.010645  4.795280
1963-06   3.37  20.75  10.623333  4.619527  3.08  14.46   8.434667  3.506356
1963-07   2.00  19.46   7.407097  4.176335  1.13  17.21   7.655806  3.675110
1963-08   5.75  24.33  12.954194  4.773159  3.29  20.62  10.708387  4.335323
1963-09   1.29  19.92  10.373667  5.402364  2.75  17.92   9.860667  3.829845
1963-10   6.25  22.00  13.830645  3.852141  3.71  18.79  12.025484  3.558906
1963-11   3.08  32.96  15.349667  7.892943  1.92  26.54  13.321333  6.341496
1963-12   4.25  32.50  14.635161  6.521537  1.08  26.54  11.677419  6.226458
1964-01   1.87  33.34  12.661290  7.287596  3.04  28.50  11.818387  6.337325
1964-02   3.67  26.20  14.114138  6.444362  2.96  25.66  12.487241  5.513780
1964-03   5.21  23.63  12.737742  4.545414  4.29  20.33  11.431613  4.220882
1964-04   5.71  18.75  12.001667  3.473976  4.08  15.79  10.374667  3.481544
1964-05   4.88  23.29  13.126129  5.085629  3.33  21.84  12.629677  4.661305
1964-06   3.54  20.41  11.712333  4.251108  2.37  17.25  10.009333  4.065651
1964-07   4.08  20.30  10.425484  3.638382  3.21  18.38   9.337742  3.628740
1964-08   3.33  21.92  10.501613  4.827111  2.00  19.12   8.300968  4.617716
1964-09   3.21  22.67  11.392000  4.551496  1.75  18.38   9.455667  4.480947
1964-10   4.88  25.17  11.856452  5.511869  2.58  21.67  10.810000  4.844315
1964-11   3.25  24.54  12.628667  5.074990  4.21  20.58  11.972000  4.486562
1964-12   4.75  28.88  15.263871  6.520151  2.25  24.17  12.455484  5.465471
1965-01   3.71  32.17  15.741613  6.711159  1.75  33.04  15.546774  7.016077
1965-02   2.92  18.75   9.282143  3.903232  2.00  15.04   6.729643  3.931648
1965-03   3.92  21.04  13.009677  5.142943  4.21  24.50  13.721935  5.460937
1965-04   4.50  26.63  13.366667  5.889386  4.88  19.38  11.741333  4.444192

           ROS         ...        CLO             BEL                    \
           min    max  ...       mean       std   min    max       mean
Yr_Mo_Dy               ...
1961-01   7.08  25.84  ...  10.107419  4.662311  5.25  27.71  13.880968
1961-02   6.08  22.42  ...  12.714286  3.568190  9.17  29.63  18.583214
1961-03   4.79  16.38  ...  11.251935  2.797977  7.21  23.45  16.410968
1961-04   2.54  18.29  ...   7.237000  2.822941  5.13  19.21  11.147333
1961-05   3.58  21.21  ...   8.499355  3.820098  4.79  28.08  11.900323
1961-06   5.13  15.50  ...   9.940333  2.549859  5.37  25.25  13.995000
1961-07   4.08  15.67  ...   8.891613  3.522505  4.21  22.17  11.092581
1961-08   2.46  17.83  ...  10.544667  3.607101  5.75  24.71  14.410000
1961-09   2.42  26.50  ...   9.931333  4.702282  4.54  23.91  13.718333
1961-10   4.21  23.09  ...  11.455806  5.741739  4.79  27.29  14.229355
1961-11   3.83  32.71  ...   8.383667  3.928784  0.71  20.46  10.776667
1961-12   2.13  29.33  ...   9.246774  4.434259  3.75  22.83  12.239355
1962-01   2.96  26.25  ...  11.498710  5.860088  0.58  29.42  16.369355
1962-02   4.29  27.16  ...  12.126429  5.276395  6.25  28.12  16.705357
1962-03   3.88  30.37  ...   8.052581  4.469026  2.21  22.46   9.690000
1962-04   4.08  27.04  ...   9.311667  4.391020  4.63  23.91  12.234333
1962-05   3.58  20.12  ...   9.293226  3.843227  3.63  23.42  12.130000
1962-06   4.00  22.54  ...  10.520333  4.844110  4.12  29.79  13.757000
1962-07   3.42  25.12  ...   8.613226  3.829465  4.67  23.13  10.783871
1962-08   4.17  19.83  ...   9.511613  3.879929  5.50  24.08  13.119032
1962-09   6.29  22.95  ...   8.286000  4.042214  2.79  26.30  11.483667
1962-10   1.96  19.21  ...   9.091290  3.734046  2.54  29.42  13.286774
1962-11   3.21  24.62  ...   8.084333  4.742454  2.46  22.29   9.786667
1962-12   6.38  33.84  ...  11.881935  5.568401  3.83  29.25  16.043548
1963-01   2.75  32.25  ...   9.390000  4.960792  0.13  23.04  11.428710
1963-02   2.71  28.75  ...  10.355714  4.822028  5.00  27.42  13.266429
1963-03   4.88  25.08  ...  11.515484  5.713630  3.17  32.63  13.982903
1963-04   4.92  29.04  ...  11.900333  4.304256  4.33  21.75  13.875667
1963-05   5.13  23.09  ...  11.394839  4.637226  4.96  32.91  14.777097
1963-06   3.67  24.13  ...   9.585333  3.527333  5.17  21.17  12.098000
1963-07   2.83  19.33  ...   8.290968  2.727111  3.71  23.42  11.404839
1963-08   4.79  19.75  ...  10.047742  3.571547  3.79  23.16  13.139355
1963-09   3.96  16.66  ...   8.988667  3.738623  3.50  26.12  13.718333
1963-10   5.63  19.55  ...  11.002581  2.964419  7.83  26.38  16.466774
1963-11   4.12  26.67  ...  10.078333  5.490191  6.25  30.00  14.932667
1963-12   5.79  27.67  ...  10.144839  5.990940  3.83  31.25  14.541935
1964-01   3.79  24.37  ...   9.676774  5.479828  3.88  36.95  15.067419
1964-02   3.67  24.54  ...  12.339655  5.095520  4.92  26.92  14.900690
1964-03   4.71  29.08  ...  10.865806  4.739561  4.38  23.38  12.353548
1964-04   4.83  24.79  ...  10.724333  3.262493  6.29  21.96  13.252333
1964-05   6.67  24.00  ...  11.783226  3.928999  7.46  29.00  16.095161
1964-06   1.83  26.12  ...  10.181000  3.368516  6.96  22.75  13.074000
1964-07   2.50  18.05  ...   9.395806  3.700741  6.29  23.83  13.232581
1964-08   3.67  18.88  ...   8.773226  4.022147  3.50  24.83  11.137097
1964-09   3.46  20.12  ...   9.590000  3.630237  4.08  25.00  13.469333
1964-10   2.37  18.71  ...   8.846129  3.181600  4.42  22.34  12.506452
1964-11   6.13  21.59  ...   9.592667  4.676093  1.50  30.88  14.509333
1964-12   4.63  27.50  ...  10.840323  3.870333  3.04  30.46  15.342258
1965-01   6.34  27.12  ...  11.706129  5.011868  3.33  39.04  16.196129
1965-02   5.79  19.33  ...   7.345714  4.000268  2.04  20.21   7.881786
1965-03   3.75  28.42  ...  11.606774  3.281082  6.34  25.17  14.807419
1965-04   3.71  20.58  ...  11.155667  4.714974  4.08  24.08  14.277667

                     MAL
               std   min    max       mean       std
Yr_Mo_Dy
1961-01   6.106738  5.17  27.63  14.703226  5.725810
1961-02   5.570494  6.67  23.87  15.411786  5.044755
1961-03   4.601365  5.54  22.95  15.720000  4.309926
1961-04   3.738132  2.67  20.46  10.278333  4.344710
1961-05   5.340704  3.33  26.58  12.011613  5.769990
1961-06   4.842142  5.96  24.71  14.553793  4.549806
1961-07   4.814853  5.41  25.37  12.312903  5.076839
1961-08   5.220775  5.88  24.30  14.345333  4.942748
1961-09   6.263875  3.37  33.09  12.921667  6.012913
1961-10   5.916125  4.04  33.45  16.793226  7.699375
1961-11   5.491954  2.00  23.58  12.146000  6.585729
1961-12   5.458657  2.62  29.33  13.098710  5.783170
1962-01   7.700364  3.25  27.00  15.661613  6.435840
1962-02   6.322833  3.04  33.50  18.426786  7.754850
1962-03   5.327341  2.46  21.29  11.509000  5.183691
1962-04   5.167285  2.21  23.58  11.780667  5.170723
1962-05   4.237583  3.25  32.17  12.922581  6.282493
1962-06   6.804684  4.29  28.38  15.218333  7.066653
1962-07   4.411158  2.29  20.83  11.326129  5.563080
1962-08   5.162007  6.92  29.95  15.420968  5.891348
1962-09   5.574105  0.67  23.00  12.313333  5.553108
1962-10   7.252034  5.04  29.17  14.090323  6.623130
1962-11   5.460824  3.00  31.34  13.298333  7.254383
1962-12   6.287572  7.87  37.63  20.074516  7.410098
1963-01   5.848756  4.54  34.13  18.822258  8.764203
1963-02   5.538518  4.54  31.00  17.120714  7.602426
1963-03   6.518180  3.08  30.09  14.132581  6.771387
1963-04   4.467014  6.92  32.96  16.333667  6.309140
1963-05   5.936026  1.75  28.01  14.975161  6.415359
1963-06   4.525927  2.79  24.25  11.358667  5.457165
1963-07   4.472383  5.17  18.50  10.840323  3.722901
1963-08   4.193548  2.25  23.29  12.580645  5.084629
1963-09   5.386193  6.25  33.42  15.146333  5.897251
1963-10   4.412610  9.62  28.50  16.870645  4.585279
1963-11   6.048949  2.96  33.87  15.425667  7.006829
1963-12   8.432771  4.25  31.75  16.530968  7.576155
1964-01   7.488686  3.63  28.96  14.145484  6.702090
1964-02   5.361650  7.71  30.91  16.857586  5.808671
1964-03   5.588231  5.25  32.88  15.409355  7.571929
1964-04   4.524387  5.79  21.71  14.187667  4.351892
1964-05   6.015118  4.46  26.30  14.575161  6.237309
1964-06   4.361561  4.71  23.58  14.147667  4.397461
1964-07   4.866047  4.50  28.46  15.272903  5.804961
1964-08   5.448617  4.29  30.46  12.241935  6.065881
1964-09   4.799762  3.67  22.42  14.236000  4.525064
1964-10   5.016384  3.58  28.04  13.676774  5.114343
1964-11   7.161606  3.63  32.46  16.231667  6.957745
1964-12   6.380830  5.25  28.62  18.040000  5.646729
1965-01   7.822574  7.79  28.58  17.888710  5.510000
1965-02   4.524401  4.83  32.63  13.530714  6.314849
1965-03   4.808359  6.58  29.58  17.660323  6.063765
1965-04   4.846535  4.75  29.46  16.379667  6.235820

[52 rows x 48 columns]